### ISSUE TITLE
Search - RESERVE does nothing in the search results

### ISSUE THREAD

**Issue by paquinem** [inf6150-doublej/backend#45]
When you do a search, clicking on RESERVE does nothing.

There needs to be a confirmation popup and then redirect to home page.

**Comment by paquinem** [comment]
[2019-06-05 21:34:45,190] ERROR in app: Exception on /reservation [POST]
Traceback (most recent call last):
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\emilie\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Emilie\Desktop\inf5140\backend\app.py", line 155, in reservation
    user_id = int(user['id'])
KeyError: 'id'

**Comment by paquinem** [comment]
Works -> Maybe make a popup instead
